### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bell-kevin**
fixed typo
license fix

### CODE REVIEW

**Comment by Jxck-S** [comment]
Whats wrong with the license?

**Comment by bell-kevin** [comment]
https://www.gnu.org/licenses/why-affero-gpl.html

**Comment by makrsmark** [comment]
license change won't happen - Jxck-S has source files that are purposefully not checked in. Changing the license would mean he has to publish them. Example is `lookup_route.py` - https://github.com/Jxck-S/plane-notify/blob/multi/planeClass.py#L221

**Comment by bell-kevin** [comment]
So his stuff is not totally open-source? Is that what you're saying, @makrsmark ?

**Pull request closed without merging**
