### PR TITLE
Send through Telegram feature | Link fix on README.md | Remove Google Ads from ss

### PR DESCRIPTION
**Pull request by rcbonz**
Added send data using Telegram Bot.
Simple link to References.md fix in README.md.
Also, in my case a Google Ads was present on screenshot. Added few lines of code to delete the element.

### CODE REVIEW

**Comment by hDmtP** [comment]
Nice

**Review by hDmtP — COMMENTED** [review]
lgtm

**Comment by rcbonz** [comment]
> lgtm

Tks! I'm noob in coding and first timer in pull request, do I need to do anything else?

**Comment by hDmtP** [comment]
> > lgtm
> 
> Tks! I'm noob in coding and first timer in pull request, do I need to do anything else?

Well I am not that much of a pro myself but for a first timer this is pretty good.

**Comment by rcbonz** [comment]
> > > lgtm
> > 
> > 
> > Tks! I'm noob in coding and first timer in pull request, do I need to do anything else?
> 
> Well I am not that much of a pro myself but for a first timer this is pretty good.

Tks!

**Comment by Jxck-S** [comment]
Thanks, I gotta test it, I was meaning to add ad removal, I never needed to because I use DNS Adblock at my house. The telegram is also a great feature.

**Comment by rcbonz** [comment]
> Thanks, I gotta test it, I was meaning to add ad removal, I never needed to because I use DNS Adblock at my house. The telegram is also a great feature.

Sounds good! Google ad remover worked on my Mac OS and since I'm from Brazil, checking if it works seems a great idea. Let me know if you need any additional information that I can provide.

**Comment by rcbonz** [comment]
> Thanks, I gotta test it, I was meaning to add ad removal, I never needed to because I use DNS Adblock at my house. The telegram is also a great feature.

Howdy. Just noticed a minor change that need to be done: in plane1.ini, remove  line 46 (TITLE = Title Of Telegram message). Telegram message doesn't have title. Since I'm noob in git, idk if I change here and update the request or maybe it's just better wait if it'll be merged and remove after. Thoughts? Tks.

**Review by Jxck-S — COMMENTED** [review]
Works great for the most part! The title is usually just a field I prepend at beginning of the messages. If you look at the Discord title and Twitter title you'll get an idea. Also, can you change where it checks to see if Telegram is enabled everywhere to also check if the Telegram section even exists, I have so many planes configured It would take me forever just to add the field to disable them? 
From
`if self.config.getboolean('TELEGRAM', 'ENABLE'):`
To
`if self.config.has_section('TELEGRAM') and self.config.getboolean('TELEGRAM', 'ENABLE'):`

**Review by rcbonz — COMMENTED** [review]
Great idea. Changed from:
```if self.config.getboolean('TELEGRAM', 'ENABLE'):```
To: 
```if self.config.has_section('TELEGRAM') and self.config.getboolean('TELEGRAM', 'ENABLE'):```
Tested here and works fine.

**Pull request merged**
